-- ============================================================
-- AML Transaction Monitoring System
-- File: 03_detection_engine.sql
-- Purpose: Thirteen detection methods covering cash deposits,
--          cash withdrawals, multi-branch activity, geographic
--          risk, and dormant account activation.
--
-- IMPORTANT: Every threshold in this file is read from the
-- alert_parameters table. Nothing is hardcoded.
-- To change a threshold, update alert_parameters.
-- No SQL queries need to be modified.
--
-- Detection methods in this file:
--   1.  Standard deviation — how consistent are deposits?
--   2.  Z-score per transaction — how unusual is each deposit?
--   3.  Moving average trend — is the trend rising?
--   4.  Peer group benchmarking — unusual vs similar accounts?
--   5.  Main monthly flag — current month vs 12-month baseline
--   6.  Structuring — monthly — deposits near $10,000 threshold
--   7.  Structuring — weekly — same pattern within 7 days
--   8.  Multi-branch deposits — using different branches
--   9.  Velocity change — month over month jump
--   10. Round number analysis — too many exact dollar amounts
--   11. Withdrawal after deposit — money in then quickly out
--   12. Geographic risk — transactions linked to high-risk countries
--   13. Dormant account activation — quiet then suddenly active
-- ============================================================


-- ============================================================
-- DETECTION 1: STANDARD DEVIATION
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5318(g) — SAR filing
-- obligation. Understanding normal account behavior is
-- required to identify what is abnormal.
--
-- Plain English: this measures how consistent or variable
-- each account's deposits are over time.
--
-- Why low variation can be suspicious: real businesses
-- fluctuate with seasons, weekends, and local events.
-- Deposits that are almost identical every month suggest
-- the amounts are being controlled, not generated by
-- real business activity.
--
-- Why the 12-month window: one year captures seasonal
-- cycles. A shorter window might flag seasonal peaks
-- as anomalies. The 12-month look-back is consistent
-- with industry practice and FFIEC examination guidance.
-- ============================================================

\echo ''
\echo '── DETECTION 1: Standard Deviation ──────────────────────'
\echo 'How consistent or variable is each account over time?'

WITH params AS (
    SELECT MAX(CASE WHEN rule_name = 'minimum_history_months'
               THEN threshold_value END) AS min_history
    FROM alert_parameters WHERE is_active = TRUE
)
SELECT
    s.full_name,
    ba.account_type,
    COUNT(t.txn_id)                                              AS total_deposits,
    ROUND(AVG(t.amount), 2)                                      AS avg_deposit,
    ROUND(STDDEV(t.amount), 2)                                   AS std_deviation,
    -- Coefficient of variation: stddev divided by average.
    -- Expressed as a percentage.
    -- Below 5% = suspiciously consistent for a real business.
    -- Above 100% = highly variable, look for spike months.
    ROUND(
        (STDDEV(t.amount) / NULLIF(AVG(t.amount), 0)) * 100,
    1)                                                           AS variation_pct,
    CASE
        WHEN STDDEV(t.amount) / NULLIF(AVG(t.amount), 0) < 0.05
            THEN 'FLAG: Too consistent for a cash business'
        WHEN STDDEV(t.amount) / NULLIF(AVG(t.amount), 0) > 1.0
            THEN 'FLAG: High variation — look for spike months'
        ELSE 'Normal'
    END                                                          AS assessment
FROM transactions t
JOIN bank_accounts ba ON t.account_id = ba.account_id
JOIN subjects s       ON ba.subject_id = s.subject_id
CROSS JOIN params
WHERE t.txn_type = 'cash_deposit'
GROUP BY s.full_name, ba.account_type, ba.account_id
HAVING COUNT(t.txn_id) >= (SELECT min_history FROM params)
ORDER BY variation_pct ASC;


-- ============================================================
-- DETECTION 2: Z-SCORE PER TRANSACTION
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5318(g) and 31 CFR
-- 1020.320 — SAR filing required when there is reason to
-- suspect funds involve illegal activity. Z-score analysis
-- provides a statistical basis for that suspicion.
--
-- Plain English: how unusual is this one deposit compared
-- to what is normal for this account?
--
-- z = 0    exactly average. Nothing unusual.
-- z = 2    two standard deviations above average. Unusual.
-- z = 3+   very unusual. High alert.
-- z = -2   significantly below average.
--
-- Why thresholds are read from alert_parameters:
-- compliance officers may need to raise or lower these
-- thresholds based on alert volume and examination findings.
-- ============================================================

\echo ''
\echo '── DETECTION 2: Z-Score Per Transaction ──────────────────'
\echo 'How unusual is each deposit compared to that account?'

WITH params AS (
    SELECT
        MAX(CASE WHEN rule_name = 'velocity_flag_threshold'
            THEN threshold_value END)       AS flag_threshold,
        MAX(CASE WHEN rule_name = 'velocity_high_alert_threshold'
            THEN threshold_value END)       AS high_threshold
    FROM alert_parameters WHERE is_active = TRUE
),
account_stats AS (
    SELECT
        account_id,
        AVG(amount)    AS account_avg,
        STDDEV(amount) AS account_stddev
    FROM transactions
    WHERE txn_type = 'cash_deposit'
    GROUP BY account_id
)
SELECT
    s.full_name,
    t.txn_date,
    t.amount,
    ROUND(st.account_avg, 2)                                     AS account_avg,
    ROUND(st.account_stddev, 2)                                  AS account_stddev,
    ROUND(
        (t.amount - st.account_avg)
        / NULLIF(st.account_stddev, 0),
    2)                                                           AS z_score,
    CASE
        WHEN (t.amount - st.account_avg)
             / NULLIF(st.account_stddev, 0)
             > p.high_threshold
            THEN 'HIGH ALERT: Above high alert threshold'
        WHEN (t.amount - st.account_avg)
             / NULLIF(st.account_stddev, 0)
             > p.flag_threshold
            THEN 'FLAG: Above flag threshold'
        WHEN (t.amount - st.account_avg)
             / NULLIF(st.account_stddev, 0)
             < -p.flag_threshold
            THEN 'FLAG: Significantly below average'
        ELSE 'Normal'
    END                                                          AS alert_level
FROM transactions t
JOIN bank_accounts ba ON t.account_id = ba.account_id
JOIN subjects s       ON ba.subject_id = s.subject_id
JOIN account_stats st ON t.account_id = st.account_id
CROSS JOIN params p
WHERE t.txn_type = 'cash_deposit'
ORDER BY
    (t.amount - st.account_avg)
    / NULLIF(st.account_stddev, 0) DESC NULLS LAST
LIMIT 20;


-- ============================================================
-- DETECTION 3: MOVING AVERAGE TREND
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5318(g). FinCEN guidance
-- on identifying patterns of suspicious activity rather than
-- relying solely on single-transaction analysis.
--
-- Plain English: instead of comparing just this month to
-- the average, a moving average smooths out short-term
-- noise to show the underlying trend.
--
-- A 3-month moving average compared to a 6-month moving
-- average shows when short-term behavior breaks away from
-- the longer trend. This catches gradual escalation that
-- single-month analysis misses.
-- ============================================================

\echo ''
\echo '── DETECTION 3: Moving Average Trend ─────────────────────'
\echo 'Is the trend rising? Smoothed monthly view per account.'

WITH monthly AS (
    SELECT
        ba.account_id,
        s.full_name,
        DATE_TRUNC('month', t.txn_date) AS txn_month,
        SUM(t.amount)                    AS monthly_total,
        COUNT(t.txn_id)                  AS deposit_count
    FROM transactions t
    JOIN bank_accounts ba ON t.account_id = ba.account_id
    JOIN subjects s       ON ba.subject_id = s.subject_id
    WHERE t.txn_type = 'cash_deposit'
    GROUP BY ba.account_id, s.full_name,
             DATE_TRUNC('month', t.txn_date)
)
SELECT
    full_name,
    TO_CHAR(txn_month, 'Mon YYYY')         AS month,
    ROUND(monthly_total, 2)                AS this_month,
    deposit_count,
    -- 3-month moving average
    ROUND(AVG(monthly_total) OVER (
        PARTITION BY account_id
        ORDER BY txn_month
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ), 2)                                  AS moving_avg_3mo,
    -- 6-month moving average
    ROUND(AVG(monthly_total) OVER (
        PARTITION BY account_id
        ORDER BY txn_month
        ROWS BETWEEN 5 PRECEDING AND CURRENT ROW
    ), 2)                                  AS moving_avg_6mo,
    -- How far above the 3-month average is this month?
    ROUND(monthly_total - AVG(monthly_total) OVER (
        PARTITION BY account_id
        ORDER BY txn_month
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ), 2)                                  AS above_3mo_avg
FROM monthly
ORDER BY full_name, txn_month;


-- ============================================================
-- DETECTION 4: PEER GROUP BENCHMARKING
-- ============================================================
-- Regulatory basis: FinCEN Customer Due Diligence Final
-- Rule 31 CFR 1010.230. CDD requires understanding expected
-- account activity for each customer type. Peer group
-- comparison is the statistical method for establishing
-- what is expected for a given business category.
--
-- Plain English: compare each account to other accounts
-- of the same business type. A flower shop is compared
-- to flower shops, not restaurants.
--
-- Why this catches what z-scores miss: an account that
-- has consistently deposited $9,000 per month for a year
-- will never trigger a velocity z-score because it has
-- not changed. But if every other flower shop deposits
-- $2,800 per month, that account is depositing more
-- than three times the peer average — a major anomaly.
-- ============================================================

\echo ''
\echo '── DETECTION 4: Peer Group Benchmarking ──────────────────'
\echo 'How does each account compare to similar business types?'

WITH params AS (
    SELECT MAX(CASE WHEN rule_name = 'peer_group_flag_threshold'
               THEN threshold_value END) AS peer_threshold
    FROM alert_parameters WHERE is_active = TRUE
),
account_monthly_avg AS (
    SELECT
        ba.account_id,
        ba.account_type,
        s.full_name,
        AVG(monthly_total) AS acct_avg
    FROM (
        SELECT account_id,
               DATE_TRUNC('month', txn_date) AS m,
               SUM(amount) AS monthly_total
        FROM transactions
        WHERE txn_type = 'cash_deposit'
        GROUP BY account_id, DATE_TRUNC('month', txn_date)
    ) monthly
    JOIN bank_accounts ba ON monthly.account_id = ba.account_id
    JOIN subjects s       ON ba.subject_id = s.subject_id
    GROUP BY ba.account_id, ba.account_type, s.full_name
),
peer_stats AS (
    SELECT
        account_type,
        AVG(acct_avg)    AS peer_avg,
        STDDEV(acct_avg) AS peer_stddev,
        COUNT(*)         AS accounts_in_group
    FROM account_monthly_avg
    GROUP BY account_type
)
SELECT
    a.full_name,
    a.account_type,
    p.accounts_in_group,
    ROUND(a.acct_avg, 2)                               AS this_acct_avg,
    ROUND(p.peer_avg, 2)                               AS peer_group_avg,
    ROUND(p.peer_stddev, 2)                            AS peer_stddev,
    ROUND(
        (a.acct_avg - p.peer_avg)
        / NULLIF(p.peer_stddev, 0),
    2)                                                 AS peer_z_score,
    ROUND(
        ((a.acct_avg - p.peer_avg)
        / NULLIF(p.peer_avg, 0)) * 100,
    1)                                                 AS pct_above_peer,
    CASE
        WHEN (a.acct_avg - p.peer_avg)
             / NULLIF(p.peer_stddev, 0)
             > params.peer_threshold
            THEN 'FLAG: Significantly above peer group'
        WHEN (a.acct_avg - p.peer_avg)
             / NULLIF(p.peer_stddev, 0)
             < -params.peer_threshold
            THEN 'NOTE: Significantly below peer group'
        ELSE 'Within normal peer range'
    END                                                AS peer_assessment
FROM account_monthly_avg a
JOIN peer_stats p ON a.account_type = p.account_type
CROSS JOIN params
ORDER BY a.account_type, peer_z_score DESC;


-- ============================================================
-- DETECTION 5: MAIN MONTHLY FLAG QUERY
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5318(g) and 31 CFR
-- 1020.320. SAR must be filed within 30 days of detecting
-- suspicious activity of $5,000 or more. This query is
-- the primary monthly detection run that generates the
-- analyst alert queue.
--
-- Plain English: for every account, compare this month's
-- total deposits to the average of the prior 12 months.
-- If the current month is more than a set number of
-- standard deviations above the average, fire an alert.
--
-- Why 12 months for the baseline: one year captures a full
-- seasonal cycle. Shorter windows may flag legitimate
-- seasonal peaks. Longer windows may dilute the signal
-- from a genuine change in behavior.
--
-- Why 3 months minimum history: fewer than 3 data points
-- produces an unreliable average and standard deviation.
-- These accounts are flagged for manual review instead.
-- ============================================================

\echo ''
\echo '── DETECTION 5: Main Monthly Flag Query ──────────────────'
\echo 'Current month vs 12-month baseline. Primary alert trigger.'

WITH params AS (
    SELECT
        MAX(CASE WHEN rule_name = 'velocity_flag_threshold'
            THEN threshold_value END)      AS flag_thresh,
        MAX(CASE WHEN rule_name = 'velocity_high_alert_threshold'
            THEN threshold_value END)      AS high_thresh,
        MAX(CASE WHEN rule_name = 'minimum_history_months'
            THEN threshold_value END)      AS min_history
    FROM alert_parameters WHERE is_active = TRUE
),
monthly AS (
    SELECT
        ba.account_id, s.full_name, ba.account_type,
        DATE_TRUNC('month', t.txn_date) AS txn_month,
        SUM(t.amount)                    AS monthly_total,
        COUNT(t.txn_id)                  AS deposit_count
    FROM transactions t
    JOIN bank_accounts ba ON t.account_id = ba.account_id
    JOIN subjects s       ON ba.subject_id = s.subject_id
    WHERE t.txn_type = 'cash_deposit'
    GROUP BY ba.account_id, s.full_name, ba.account_type,
             DATE_TRUNC('month', t.txn_date)
),
rolling AS (
    SELECT *,
        AVG(monthly_total) OVER (
            PARTITION BY account_id ORDER BY txn_month
            ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING
        ) AS prior_avg,
        STDDEV(monthly_total) OVER (
            PARTITION BY account_id ORDER BY txn_month
            ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING
        ) AS prior_stddev,
        COUNT(monthly_total) OVER (
            PARTITION BY account_id ORDER BY txn_month
            ROWS BETWEEN 12 PRECEDING AND 1 PRECEDING
        ) AS months_of_history
    FROM monthly
),
scored AS (
    SELECT *,
        CASE WHEN prior_stddev > 0
             THEN (monthly_total - prior_avg) / prior_stddev
             ELSE NULL END AS z_score
    FROM rolling
    WHERE txn_month = DATE_TRUNC('month', CURRENT_DATE)
)
SELECT
    s2.full_name                                        AS account_holder,
    sc.account_type,
    ROUND(sc.monthly_total, 2)                          AS current_month_total,
    sc.deposit_count,
    ROUND(sc.prior_avg, 2)                              AS prior_12mo_avg,
    ROUND(sc.prior_stddev, 2)                           AS prior_stddev,
    sc.months_of_history,
    ROUND(sc.z_score, 2)                                AS z_score,
    ROUND(sc.monthly_total - sc.prior_avg, 2)           AS amount_above_avg,
    ROUND(((sc.monthly_total - sc.prior_avg)
        / NULLIF(sc.prior_avg, 0)) * 100, 1)            AS pct_increase,
    CASE
        WHEN sc.z_score >= p.high_thresh
            THEN 'HIGH ALERT'
        WHEN sc.z_score >= p.flag_thresh
            THEN 'FLAG'
        WHEN sc.z_score >= 1.5
            THEN 'WATCH'
        WHEN sc.months_of_history < p.min_history
            THEN 'MANUAL REVIEW — insufficient history'
        ELSE 'Normal'
    END                                                 AS alert_level
FROM scored sc
JOIN bank_accounts ba2 ON sc.account_id = ba2.account_id
JOIN subjects s2       ON ba2.subject_id = s2.subject_id
CROSS JOIN params p
WHERE sc.months_of_history >= p.min_history
ORDER BY sc.z_score DESC NULLS LAST;


-- ============================================================
-- DETECTION 6: STRUCTURING — MONTHLY
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5324 — structuring
-- prohibition. It is a federal crime to break up transactions
-- specifically to avoid the $10,000 CTR reporting threshold
-- under 31 CFR 1010.311. This is true regardless of whether
-- the money itself came from a legal source.
--
-- Plain English: counts how many deposits in a month
-- fall in the zone just below the $10,000 reporting limit.
-- Three or more in one month is a high alert.
--
-- Note: the CTR threshold and the structuring floor are
-- both read from alert_parameters so they can be updated
-- if regulatory thresholds change.
-- ============================================================

\echo ''
\echo '── DETECTION 6: Structuring — Monthly ────────────────────'
\echo 'Deposits clustered just below the $10,000 reporting limit.'

WITH params AS (
    SELECT
        MAX(CASE WHEN rule_name = 'structuring_zone_floor'
            THEN threshold_value END)        AS zone_floor,
        MAX(CASE WHEN rule_name = 'structuring_zone_ceiling'
            THEN threshold_value END)        AS zone_ceiling,
        MAX(CASE WHEN rule_name = 'structuring_high_alert_count'
            THEN threshold_value END)        AS high_count
    FROM alert_parameters WHERE is_active = TRUE
),
monthly_struct AS (
    SELECT
        ba.account_id,
        s.full_name,
        DATE_TRUNC('month', t.txn_date)    AS txn_month,
        COUNT(*) FILTER (
            WHERE t.amount BETWEEN
                (SELECT zone_floor  FROM params) AND
                (SELECT zone_ceiling FROM params)
        )                                  AS deposits_in_zone,
        SUM(t.amount) FILTER (
            WHERE t.amount BETWEEN
                (SELECT zone_floor  FROM params) AND
                (SELECT zone_ceiling FROM params)
        )                                  AS total_in_zone,
        SUM(t.amount)                      AS total_all
    FROM transactions t
    JOIN bank_accounts ba ON t.account_id = ba.account_id
    JOIN subjects s       ON ba.subject_id = s.subject_id
    WHERE t.txn_type = 'cash_deposit'
    GROUP BY ba.account_id, s.full_name,
             DATE_TRUNC('month', t.txn_date)
)
SELECT
    full_name,
    TO_CHAR(txn_month, 'Mon YYYY')        AS month,
    deposits_in_zone,
    ROUND(total_in_zone, 2)               AS total_in_zone,
    ROUND(total_all, 2)                   AS total_all_deposits,
    CASE
        WHEN deposits_in_zone >= (SELECT high_count FROM params)
            THEN 'HIGH ALERT: 3+ deposits in structuring zone'
        WHEN deposits_in_zone = 2
            THEN 'FLAG: 2 deposits in structuring zone'
        WHEN deposits_in_zone = 1
            THEN 'WATCH: 1 deposit in structuring zone'
        ELSE 'No structuring pattern'
    END                                   AS structuring_flag
FROM monthly_struct
WHERE deposits_in_zone > 0
ORDER BY deposits_in_zone DESC, txn_month DESC;


-- ============================================================
-- DETECTION 7: STRUCTURING — WEEKLY (7-DAY ROLLING WINDOW)
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5324. Monthly structuring
-- detection only catches patterns spread across a calendar
-- month. More aggressive structuring can happen within a
-- single week. A 7-day rolling window catches this.
--
-- Plain English: looks at every possible 7-day window and
-- counts how many below-threshold deposits occurred.
-- Two or more in one week is more urgent than two in a month
-- because the time compression shows greater intent.
-- ============================================================

\echo ''
\echo '── DETECTION 7: Structuring — Weekly Window ──────────────'
\echo 'Two or more near-threshold deposits within any 7 days.'

WITH params AS (
    SELECT
        MAX(CASE WHEN rule_name = 'structuring_zone_floor'
            THEN threshold_value END)   AS zone_floor,
        MAX(CASE WHEN rule_name = 'structuring_zone_ceiling'
            THEN threshold_value END)   AS zone_ceiling,
        MAX(CASE WHEN rule_name = 'structuring_week_count'
            THEN threshold_value END)   AS week_count
    FROM alert_parameters WHERE is_active = TRUE
),
zone_deposits AS (
    SELECT
        t.txn_id,
        ba.account_id,
        s.full_name,
        t.txn_date,
        t.amount
    FROM transactions t
    JOIN bank_accounts ba ON t.account_id = ba.account_id
    JOIN subjects s       ON ba.subject_id = s.subject_id
    CROSS JOIN params p
    WHERE t.txn_type = 'cash_deposit'
      AND t.amount BETWEEN p.zone_floor AND p.zone_ceiling
),
weekly_counts AS (
    SELECT
        a.account_id,
        a.full_name,
        a.txn_date                                    AS window_start,
        a.txn_date + 6                                AS window_end,
        COUNT(b.txn_id)                               AS deposits_in_window,
        SUM(b.amount)                                 AS total_in_window
    FROM zone_deposits a
    JOIN zone_deposits b
        ON a.account_id = b.account_id
        AND b.txn_date BETWEEN a.txn_date AND a.txn_date + 6
    GROUP BY a.account_id, a.full_name, a.txn_date
)
SELECT
    full_name,
    window_start,
    window_end,
    deposits_in_window,
    ROUND(total_in_window, 2)                         AS total_in_window,
    CASE
        WHEN deposits_in_window >= (SELECT week_count FROM params)
            THEN 'HIGH ALERT: Multiple near-threshold deposits in one week'
        ELSE 'Watch'
    END                                               AS weekly_flag
FROM weekly_counts
WHERE deposits_in_window >= (SELECT week_count FROM params)
ORDER BY deposits_in_window DESC, window_start DESC;


-- ============================================================
-- DETECTION 8: MULTI-BRANCH DEPOSIT DETECTION
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5324. Using multiple
-- branches to deposit cash is a documented method of
-- structuring. The intent is to avoid having one teller
-- observe a pattern of below-threshold deposits.
-- FinCEN guidance identifies multi-branch activity as
-- a primary structuring indicator.
--
-- Plain English: counts how many different branches an
-- account used in a single month. Using two or more
-- branches is flagged. Each branch appears separately
-- so the pattern is visible.
-- ============================================================

\echo ''
\echo '── DETECTION 8: Multi-Branch Deposit Detection ───────────'
\echo 'Same account using different branches in the same month.'

WITH params AS (
    SELECT MAX(CASE WHEN rule_name = 'multi_branch_threshold'
               THEN threshold_value END) AS branch_thresh
    FROM alert_parameters WHERE is_active = TRUE
),
monthly_branches AS (
    SELECT
        ba.account_id,
        s.full_name,
        DATE_TRUNC('month', t.txn_date)  AS txn_month,
        COUNT(DISTINCT t.branch)          AS branch_count,
        STRING_AGG(DISTINCT t.branch,
                   ', ' ORDER BY t.branch) AS branches_used,
        COUNT(t.txn_id)                   AS total_deposits,
        SUM(t.amount)                     AS total_amount
    FROM transactions t
    JOIN bank_accounts ba ON t.account_id = ba.account_id
    JOIN subjects s       ON ba.subject_id = s.subject_id
    WHERE t.txn_type = 'cash_deposit'
      AND t.branch IS NOT NULL
    GROUP BY ba.account_id, s.full_name,
             DATE_TRUNC('month', t.txn_date)
)
SELECT
    full_name,
    TO_CHAR(txn_month, 'Mon YYYY')   AS month,
    branch_count,
    branches_used,
    total_deposits,
    ROUND(total_amount, 2)            AS total_deposited,
    CASE
        WHEN branch_count >= (SELECT branch_thresh FROM params)
            THEN 'FLAG: Deposits spread across multiple branches'
        ELSE 'Single branch'
    END                               AS branch_flag
FROM monthly_branches
WHERE branch_count >= (SELECT branch_thresh FROM params)
ORDER BY branch_count DESC, txn_month DESC;


-- ============================================================
-- DETECTION 9: VELOCITY CHANGE (MONTH OVER MONTH)
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5318(g). Sudden changes
-- in account activity are a primary indicator of suspicious
-- activity under FinCEN SAR guidance.
--
-- Plain English: compares each month to the previous month.
-- A jump of more than 100% in one month is flagged.
-- A jump of more than 500% is a high alert.
--
-- LAG is a SQL function that retrieves the value from
-- the previous row. Here it gets last month's total
-- so we can calculate the percentage change.
-- ============================================================

\echo ''
\echo '── DETECTION 9: Velocity Change Month Over Month ─────────'
\echo 'How much did deposits jump compared to last month?'

WITH monthly AS (
    SELECT
        ba.account_id, s.full_name,
        DATE_TRUNC('month', t.txn_date) AS txn_month,
        COUNT(t.txn_id)                  AS deposit_count,
        SUM(t.amount)                    AS monthly_total
    FROM transactions t
    JOIN bank_accounts ba ON t.account_id = ba.account_id
    JOIN subjects s       ON ba.subject_id = s.subject_id
    WHERE t.txn_type = 'cash_deposit'
    GROUP BY ba.account_id, s.full_name,
             DATE_TRUNC('month', t.txn_date)
)
SELECT
    full_name,
    TO_CHAR(txn_month, 'Mon YYYY')                           AS month,
    ROUND(monthly_total, 2)                                  AS this_month,
    ROUND(LAG(monthly_total) OVER (
        PARTITION BY account_id ORDER BY txn_month
    ), 2)                                                    AS prior_month,
    ROUND(monthly_total - LAG(monthly_total) OVER (
        PARTITION BY account_id ORDER BY txn_month
    ), 2)                                                    AS change,
    ROUND(
        ((monthly_total - LAG(monthly_total) OVER (
            PARTITION BY account_id ORDER BY txn_month
        )) / NULLIF(LAG(monthly_total) OVER (
            PARTITION BY account_id ORDER BY txn_month
        ), 0)) * 100,
    1)                                                       AS pct_change,
    CASE
        WHEN ((monthly_total - LAG(monthly_total) OVER (
                PARTITION BY account_id ORDER BY txn_month
              )) / NULLIF(LAG(monthly_total) OVER (
                PARTITION BY account_id ORDER BY txn_month
              ), 0)) > 5.0
            THEN 'HIGH ALERT: Over 500% increase'
        WHEN ((monthly_total - LAG(monthly_total) OVER (
                PARTITION BY account_id ORDER BY txn_month
              )) / NULLIF(LAG(monthly_total) OVER (
                PARTITION BY account_id ORDER BY txn_month
              ), 0)) > 1.0
            THEN 'FLAG: Over 100% increase'
        ELSE 'Normal'
    END                                                      AS velocity_flag
FROM monthly
ORDER BY full_name, txn_month;


-- ============================================================
-- DETECTION 10: ROUND NUMBER ANALYSIS
-- ============================================================
-- Regulatory basis: FATF Typology Report — Money Laundering
-- Through Physical Transportation of Cash (October 2015).
-- Round dollar amounts are a primary indicator of pre-counted
-- criminal proceeds. Legitimate business cash rarely lands
-- on exact round numbers.
--
-- Plain English: what percentage of all deposits for this
-- account are exact multiples of $1,000? Over 50% is flagged.
-- ============================================================

\echo ''
\echo '── DETECTION 10: Round Number Analysis ───────────────────'
\echo 'Too many deposits at exact round dollar amounts?'

WITH params AS (
    SELECT MAX(CASE WHEN rule_name = 'round_number_flag_threshold'
               THEN threshold_value END) AS round_thresh
    FROM alert_parameters WHERE is_active = TRUE
)
SELECT
    s.full_name,
    ba.account_type,
    COUNT(*)                                                    AS total_deposits,
    COUNT(*) FILTER (WHERE t.amount % 1000 = 0)                AS round_deposits,
    ROUND(
        COUNT(*) FILTER (WHERE t.amount % 1000 = 0)::numeric
        / NULLIF(COUNT(*), 0)::numeric * 100,
    1)                                                          AS round_pct,
    CASE
        WHEN COUNT(*) FILTER (WHERE t.amount % 1000 = 0)::numeric
             / NULLIF(COUNT(*), 0)::numeric * 100
             > (SELECT round_thresh FROM params)
            THEN 'FLAG: More than half of deposits are round numbers'
        WHEN COUNT(*) FILTER (WHERE t.amount % 1000 = 0)::numeric
             / NULLIF(COUNT(*), 0)::numeric * 100
             > (SELECT round_thresh FROM params) * 0.6
            THEN 'WATCH: Elevated round number proportion'
        ELSE 'Normal'
    END                                                         AS round_flag
FROM transactions t
JOIN bank_accounts ba ON t.account_id = ba.account_id
JOIN subjects s       ON ba.subject_id = s.subject_id
WHERE t.txn_type = 'cash_deposit'
GROUP BY s.full_name, ba.account_type
ORDER BY round_pct DESC;


-- ============================================================
-- DETECTION 11: WITHDRAWAL AFTER DEPOSIT
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5318(g). Rapid movement
-- of funds — depositing cash then withdrawing it quickly
-- — is a layering typology indicator. The deposit establishes
-- a paper trail. The withdrawal moves the money onward.
--
-- Plain English: finds accounts where a large cash deposit
-- was followed by a large cash withdrawal within 5 days.
-- Money in then quickly out is suspicious.
-- ============================================================

\echo ''
\echo '── DETECTION 11: Withdrawal After Deposit ────────────────'
\echo 'Cash deposited then withdrawn within 5 days.'

SELECT
    s.full_name,
    dep.txn_date                         AS deposit_date,
    ROUND(dep.amount, 2)                 AS deposit_amount,
    dep.branch                           AS deposit_branch,
    wd.txn_date                          AS withdrawal_date,
    ROUND(wd.amount, 2)                  AS withdrawal_amount,
    wd.branch                            AS withdrawal_branch,
    wd.txn_date - dep.txn_date           AS days_between,
    ROUND(wd.amount / NULLIF(dep.amount, 0) * 100, 1)
                                         AS withdrawal_pct_of_deposit,
    'FLAG: Large withdrawal within 5 days of deposit'
                                         AS alert_flag
FROM transactions dep
JOIN transactions wd
    ON  dep.account_id = wd.account_id
    AND wd.txn_type    = 'cash_withdrawal'
    AND wd.txn_date    BETWEEN dep.txn_date AND dep.txn_date + 5
    AND wd.amount      >= dep.amount * 0.5
JOIN bank_accounts ba ON dep.account_id = ba.account_id
JOIN subjects s       ON ba.subject_id  = s.subject_id
WHERE dep.txn_type = 'cash_deposit'
  AND dep.amount   >= 5000
ORDER BY days_between ASC, dep.txn_date DESC;


-- ============================================================
-- DETECTION 12: GEOGRAPHIC RISK
-- ============================================================
-- Regulatory basis: OFAC regulations 31 CFR Part 500 et seq.
-- FinCEN Geographic Targeting Orders. FATF high-risk
-- jurisdiction lists. Transactions to or from countries
-- on these lists require enhanced scrutiny regardless
-- of the transaction amount.
--
-- Plain English: flags any account that has sent or received
-- money from a country code that appears on a risk list.
-- The list here includes FATF grey-listed jurisdictions.
-- In a production system this list would be maintained
-- separately and updated as FATF publishes new assessments.
--
-- Country codes flagged: NL (Netherlands, used in sample
-- data), and a broader set of currently monitored
-- jurisdictions for illustration.
-- ============================================================

\echo ''
\echo '── DETECTION 12: Geographic Risk ─────────────────────────'
\echo 'Transactions connected to high-risk countries.'

WITH high_risk_countries AS (
    -- In a production system this list would be pulled from
    -- a maintained reference table updated quarterly when
    -- FATF publishes new grey and black list assessments.
    -- FATF list: https://www.fatf-gafi.org/en/topics/
    --            high-risk-and-other-monitored-jurisdictions.html
    SELECT unnest(ARRAY[
        'NL',  -- Netherlands (in sample data)
        'BU',  -- Burma/Myanmar
        'CF',  -- Central African Republic
        'CD',  -- Democratic Republic of Congo
        'HT',  -- Haiti
        'IR',  -- Iran
        'IQ',  -- Iraq
        'LY',  -- Libya
        'ML',  -- Mali
        'NI',  -- Nicaragua
        'KP',  -- North Korea
        'RU',  -- Russia
        'SO',  -- Somalia
        'SS',  -- South Sudan
        'SD',  -- Sudan
        'SY',  -- Syria
        'TZ',  -- Tanzania
        'VE',  -- Venezuela
        'YE'   -- Yemen
    ]) AS country_code
)
SELECT
    s.full_name,
    t.txn_date,
    t.txn_type,
    ROUND(t.amount, 2)                  AS amount,
    t.counterparty,
    t.counterparty_bank,
    t.counterparty_country,
    'FLAG: Transaction linked to high-risk jurisdiction'
                                        AS geo_flag,
    'Verify business purpose. Consider escalation. '
    || 'Check OFAC SDN list for counterparty.'
                                        AS recommended_action
FROM transactions t
JOIN bank_accounts ba ON t.account_id = ba.account_id
JOIN subjects s       ON ba.subject_id = s.subject_id
WHERE t.counterparty_country IN (
    SELECT country_code FROM high_risk_countries
)
ORDER BY t.txn_date DESC;


-- ============================================================
-- DETECTION 13: DORMANT ACCOUNT ACTIVATION
-- ============================================================
-- Regulatory basis: BSA 31 U.S.C. 5318(g). FinCEN guidance
-- identifies reactivation of dormant accounts as a recognized
-- money laundering typology indicator. A dormant account
-- that suddenly receives large deposits may have been opened
-- and held specifically for future use in a scheme.
--
-- Plain English: finds accounts that had no transactions for
-- 90 or more days and then suddenly became active this month.
-- The longer the dormancy the more suspicious the activation.
--
-- Why 90 days: this is the standard industry threshold for
-- defining dormancy consistent with federal examination
-- guidance and peer institution practice.
-- ============================================================

\echo ''
\echo '── DETECTION 13: Dormant Account Activation ──────────────'
\echo 'Accounts that went quiet then suddenly became active.'

WITH params AS (
    SELECT MAX(CASE WHEN rule_name = 'dormant_days_threshold'
               THEN threshold_value END) AS dormant_days
    FROM alert_parameters WHERE is_active = TRUE
),
last_pre_current AS (
    -- Most recent transaction BEFORE the current month
    SELECT
        account_id,
        MAX(txn_date)  AS last_txn_before_current
    FROM transactions
    WHERE txn_date < DATE_TRUNC('month', CURRENT_DATE)
    GROUP BY account_id
),
current_month_activity AS (
    -- Activity in the current month
    SELECT
        account_id,
        COUNT(*)       AS txns_this_month,
        SUM(amount)    AS total_this_month
    FROM transactions
    WHERE txn_date >= DATE_TRUNC('month', CURRENT_DATE)
    GROUP BY account_id
)
SELECT
    s.full_name,
    lp.last_txn_before_current,
    CURRENT_DATE - lp.last_txn_before_current        AS days_dormant,
    cm.txns_this_month,
    ROUND(cm.total_this_month, 2)                    AS amount_this_month,
    CASE
        WHEN CURRENT_DATE - lp.last_txn_before_current
             >= (SELECT dormant_days FROM params) * 2
            THEN 'HIGH ALERT: Dormant 180+ days then active'
        WHEN CURRENT_DATE - lp.last_txn_before_current
             >= (SELECT dormant_days FROM params)
            THEN 'FLAG: Dormant 90+ days then active'
        ELSE 'Watch'
    END                                              AS dormant_flag
FROM last_pre_current lp
JOIN current_month_activity cm   ON lp.account_id = cm.account_id
JOIN bank_accounts ba            ON lp.account_id = ba.account_id
JOIN subjects s                  ON ba.subject_id  = s.subject_id
CROSS JOIN params
WHERE CURRENT_DATE - lp.last_txn_before_current
      >= (SELECT dormant_days FROM params)
ORDER BY days_dormant DESC;


\echo ''
\echo 'Detection engine complete.'
\echo 'All 13 detection methods executed.'
\echo 'Thresholds read from alert_parameters table throughout.'
\echo 'Next: run sql/04_alert_dashboard.sql'
